[window]
padding = { x = 8, y = 2}
dynamic_padding = true
decorations = "none"

[font]
size = 10.5 

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[colors.primary]
background = "#09090d"

[colors.normal]
black   = "#000000"
red     = "#ff5f5f"
green   = "#5fff87"
yellow  = "#ffd75f"
blue    = "#5f87ff"
magenta = "#af87ff"
cyan    = "#5fd7ff"
white   = "#e6e6e6"

[colors.bright]
black   = "#4d4d4d"
red     = "#ff6f6f"
green   = "#6fff97"
yellow  = "#ffdf7f"
blue    = "#6f97ff"
magenta = "#bf97ff"
cyan    = "#6fe7ff"
white   = "#ffffff"

