[window]
padding = { x = 8, y = 2}
dynamic_padding = true
decorations = "none"
opacity = 0.90

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[colors.primary]
background = "#1e1e2e"
foreground = "#c4ccda"

[colors.normal]
black   = "#313244"
red     = "#a06070"
green   = "#527a63"
yellow  = "#9a8a6a"
blue    = "#7090a8"
magenta = "#8a8ab0"
cyan    = "#6b9a96"
white   = "#c4ccda"

[colors.bright]
black   = "#585b70"
red     = "#b07080"
green   = "#628a73"
yellow  = "#aa9a7a"
blue    = "#8090b8"
magenta = "#9a9ac0"
cyan    = "#7baaaa"
white   = "#d4dce8"
