[window]
padding = { x = 8, y = 2}
dynamic_padding = true
decorations = "none"
opacity = 0.85

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.normal]
black   = "#282828"
red     = "#fa4d56"
green   = "#42be65"
yellow  = "#ffe97b"
blue    = "#78a9ff"
magenta = "#be95ff"
cyan    = "#33b1ff"
white   = "#dde1e7"

[colors.bright]
black   = "#525252"
red     = "#ff8389"
green   = "#57d679"
yellow  = "#ffd44c"
blue    = "#a6c8ff"
magenta = "#d4bbff"
cyan    = "#82cfff"
white   = "#f2f4f8"
